name: 'Post to slack'
description: 'Allows custom messages as part of a GitHub Actions pipeline'
inputs:
  SLACK_BOT_TOKEN:
    description: 'Your token from Slack'
    required: true
  message:
    description: 'A json file from Slack Block Kit'
    required: true
  channel:
    description: Channel to post to
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
