name: Post to Slack demo

on:
  workflow_dispatch: {}

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    name: Post to Slack demo
    steps:
    - name: Check out repo to use demo.json
      uses: actions/checkout@v2
    - name: Get some stuff to put in our slack message
      uses: Bradshaw/verbose-action-info@main
      id: verbose
    - name: Generate and post the message
      id: hello
      uses: 52-entertainment/slack-actions@main
      with:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        message: '.github/workflows/demo.json'
      env:
        V_EVENT: ${{ steps.verbose.outputs.event }}
        V_COMMIT: ${{ steps.verbose.outputs.commit_url }}
        V_SHA: ${{ steps.verbose.outputs.sha }}
